name: PR Checks

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, reopened, synchronize ]

jobs:
  check-build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - uses: nikitasavinov/checkstyle-action@master
      with:
        filter_mode: diff_context
        reporter: 'github-pr-review'
        tool_name: 'google-checks'

    - uses: kemsakurai/action-pmd@master
      with:
        rulesets_path: ./.github/workflows/pmd-java-rulesets.xml
        filter_mode: diff_context
        reporter: 'github-pr-review'
        tool_name: 'pmd-checks'

    - run: mvn -B package --file pom.xml
