name: Linting

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    types: [ opened, reopened, synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Super-Linter
      uses: github/super-linter@v4.9.7
