name: Linting

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    types: [ opened, reopened, synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Super-Linter
      uses: github/super-linter/slim@v4
      env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
